name: Lint

on: push

jobs:
  ruff:
    runs-on: ubuntu-slim

    env:
      RUFF_OUTPUT_FORMAT: github

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Install dependencies
        run: uv sync

      - name: Ruff Formatter
        run: uv run ruff format --diff .

      - name: Ruff Linter
        run: uv run ruff check .

  mypy:
    runs-on: ubuntu-slim

    strategy:
      matrix:
        uv_resolution: ["highest", "lowest-direct"]

    env:
      UV_RESOLUTION: ${{ matrix.uv_resolution }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Install dependencies
        run: uv sync

      - name: mypy
        run: uv run mypy .
